# Generated by Django 4.2.18 on 2025-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0002_alter_general_options_monthlytax_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytax',
            name='tax_percentage',
            field=models.FloatField(default=0, verbose_name='Tax percentage'),
        ),
    ]
