# Generated by Django 5.2.17 on 2026-09-08 12:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0003_alter_monthlytax_tax_percentage'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytax',
            name='alliance_tax_rate',
            field=models.FloatField(default=0, help_text='Alliance rate in effect when this row was calculated. Stored per row so changing the rate does not rewrite what past months were owed.', verbose_name='Applied alliance tax rate'),
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Share of the gross PvE income a corporation owes. 0.1 means 10 percent.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Alliance tax rate')),
                ('tax_types', models.JSONField(blank=True, default=list, help_text='Wallet journal ref_types counted as PvE income, for example bounty_prizes.', verbose_name='Taxed journal types')),
                ('last_month', models.BooleanField(default=False, help_text='Include the previous month in calculations and on the overview.')),
                ('current_month', models.BooleanField(default=False, help_text='Include the running month in calculations and on the overview.')),
                ('use_reason', models.BooleanField(default=False, help_text='Match payments by their reason code instead of by amount alone.')),
                ('corporation_blacklist', models.ManyToManyField(blank=True, help_text='Never taxed and never listed, even inside a taxed alliance.', related_name='+', to='eveonline.evecorporationinfo', verbose_name='Excluded corporations')),
                ('tax_alliances', models.ManyToManyField(blank=True, help_text='Corporations of these alliances are taxed.', related_name='+', to='eveonline.eveallianceinfo', verbose_name='Taxed alliances')),
                ('tax_corporations', models.ManyToManyField(blank=True, help_text='Corporations that receive the tax payments.', related_name='+', to='eveonline.evecorporationinfo', verbose_name='Holding corporations')),
            ],
            options={
                'verbose_name': 'Tax configuration',
            },
        ),
    ]
