# Generated by Django 5.2.17 on 2026-09-08 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0005_seed_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_min_days_per_month',
            field=models.PositiveSmallIntegerField(default=12, help_text='A character is listed once it exceeds this many suspicious days within the selected month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Bot detection: days per month'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_min_hours_per_day',
            field=models.PositiveSmallIntegerField(default=20, help_text='A day counts as suspicious when a character earned taxed income in more than this many different hours of that day.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Bot detection: hours per day'),
        ),
    ]
