# Generated by Django 5.2.17 on 2026-09-08 13:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0006_taxconfiguration_bot_min_days_per_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(help_text='First month this rate applies to. Stored as the first of that month.', unique=True, verbose_name='Valid from')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Share of the gross PvE income. 0.1 means 10 percent.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Alliance tax rate')),
            ],
            options={
                'verbose_name': 'Tax rate',
                'verbose_name_plural': 'Tax rate schedule',
                'ordering': ['-valid_from'],
            },
        ),
    ]
