# Generated by Django 5.2.17 on 2026-09-10 10:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0010_monthlytax_one_row_per_corp_and_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='tax_change_min_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.45'), help_text='In percentage points of the share of the bounty that reaches the corporation. A move smaller than this is not listed, and days within it count as one level. Nine percent to ten is one point.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Corp tax change: smallest move'),
        ),
    ]
