# Generated by Django 5.2.17 on 2026-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    """Longer help text on Match by Reason.

    State only: help_text is not stored in the database, so `sqlmigrate`
    reports this as a no-op. Nothing is locked and no table is rewritten,
    however large the journal behind it is.
    """

    dependencies = [
        ('eos_tax', '0011_taxconfiguration_tax_change_min_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfiguration',
            name='use_reason',
            field=models.BooleanField(default=False, help_text='Match payments by their reason code instead of by amount alone. Without it a payment is recognised by its amount only, so two Corporations owing the same sum, or one Corporation owing the same sum twice, cannot be told apart.'),
        ),
    ]
