# Generated by Django 5.2.17 on 2026-09-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0012_alter_taxconfiguration_use_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_run_max_gaps',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many breaks a run may contain and still count as one. A daily downtime would otherwise cut every long night in two. Only a break under an hour can be forgiven; a longer one always ends the run.', validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Unbroken run: interruptions allowed'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_run_min_ticks',
            field=models.PositiveSmallIntegerField(default=18, help_text='How many payouts in a row a character has to collect without a break before the run is listed. The game pays a ratter about every twenty minutes, so eighteen is roughly six hours.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(200)], verbose_name='Unbroken run: shortest run listed'),
        ),
    ]
