# Generated by Django 5.2.17 on 2026-09-14 07:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0013_taxconfiguration_bot_run_max_gaps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_clock_corp_min_payouts',
            field=models.PositiveSmallIntegerField(default=40, help_text="How many payouts have to be left in the Corporation once the character's own are taken out, before its middle of the day is worth comparing against.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Smallest usable yardstick'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_clock_max_apart',
            field=models.PositiveSmallIntegerField(default=12, help_text='In hours. Twelve is as far apart as two times of day can be, so the default treats the whole clock as the scale. A smaller value makes the colouring reach red sooner.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Distance counted as a full deviation'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_clock_min_payouts',
            field=models.PositiveSmallIntegerField(default=12, help_text="Below this many payouts in the month the middle of a character's day is wherever the noise landed, so they are left out.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Smallest character worth reading'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_rhythm_busy_hours',
            field=models.PositiveSmallIntegerField(default=8, help_text="How many hours of the day count as the Corporation's busy window. A character spread evenly over the clock lands on this share of any window, which is the floor the score measures down to.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)], verbose_name='Length of the busy window'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_rhythm_corp_min_payouts',
            field=models.PositiveSmallIntegerField(default=40, help_text="How many payouts have to be left in the Corporation once the character's own are taken out. Below this there is no rhythm to compare against, only noise, and the character is not scored.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Smallest usable yardstick'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_rhythm_min_payouts',
            field=models.PositiveSmallIntegerField(default=12, help_text='Below this many payouts in the month a character has too little of a day to describe, and is left out of this reading.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Smallest character worth reading'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_run_gap_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='In minutes. A break longer than this ends the run whatever the allowance above says. Without a ceiling one allowance would weld a morning and an evening into a single twelve hour run.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='Longest break a run can survive'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_run_tick_tolerance',
            field=models.PositiveSmallIntegerField(default=25, help_text='In minutes. The game pays about every twenty minutes and the tick slips, so a little more than twenty leaves room for that without calling an unbroken stretch broken.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Longest gap that still counts as the same tick'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_min_days_per_month',
            field=models.PositiveSmallIntegerField(default=12, help_text='A character is listed once it exceeds this many suspicious days within the selected month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Days in a month before a character is listed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_min_hours_per_day',
            field=models.PositiveSmallIntegerField(default=20, help_text='A day counts as suspicious when a character earned taxed income in more than this many different hours of that day.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hours in a day before it counts'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_run_max_gaps',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many breaks a run may contain and still count as one. A daily downtime would otherwise cut every long night in two. Only a break under an hour can be forgiven; a longer one always ends the run.', validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Interruptions allowed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_run_min_ticks',
            field=models.PositiveSmallIntegerField(default=18, help_text='How many payouts in a row a character has to collect without a break before the run is listed. The game pays a ratter about every twenty minutes, so eighteen is roughly six hours.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(200)], verbose_name='Shortest run listed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='tax_change_min_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.45'), help_text='In percentage points of the share of the bounty that reaches the corporation. A move smaller than this is not listed, and days within it count as one level. Nine percent to ten is one point.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Smallest move worth listing'),
        ),
    ]
