# Generated by Django 5.2.17 on 2026-09-14 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0014_taxconfiguration_bot_clock_corp_min_payouts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_hours_min_entries',
            field=models.PositiveSmallIntegerField(default=2, help_text='A single entry is noise - a stray bounty tick, one ESS payout. The game pays about every twenty minutes, so an hour of uninterrupted play holds three; two is deliberately tolerant, because play gets interrupted and a false negative costs less than accusing a player.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Entries before an hour counts as active'),
        ),
    ]
