# Generated by Django 5.2.17 on 2026-09-14 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0015_taxconfiguration_bot_hours_min_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_clock_min_apart',
            field=models.PositiveSmallIntegerField(default=4, help_text="In hours. How far from their Corporation a character's day has to sit before the list mentions them. Four is a third of the twelve above, which is where the colouring stops calling a distance unremarkable.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Smallest distance listed'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_rhythm_min_difference',
            field=models.PositiveSmallIntegerField(default=10, help_text='In percentage points. How much flatter than the rest of their Corporation a character has to be before the list mentions them. A negative difference means more concentrated than the Corporation, which is the opposite of what this looks for, so those are never listed whatever this says.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Smallest difference listed'),
        ),
    ]
