# Generated by Django 5.2.17 on 2026-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0016_taxconfiguration_bot_clock_min_apart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_clock_purge_strong',
            field=models.BooleanField(default=True, help_text="The same for this reading: a character far enough from their Corporation to be listed also pulls the Corporation's own middle of the day towards themselves, which shortens everybody else's distance.", verbose_name='Leave flagged characters out of the yardstick'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_rhythm_purge_strong',
            field=models.BooleanField(default=True, help_text="A character flat enough to be listed is also part of their Corporation's day, and drags it flat with them - which makes everybody else look ordinary. With this on the reading runs twice: once to find them, once with them taken out. A Corporation that would fall below the floor above keeps the plain figure.", verbose_name='Leave flagged characters out of the yardstick'),
        ),
    ]
