# Generated by Django 5.2.17 on 2026-09-14 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0017_taxconfiguration_bot_clock_purge_strong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_clock_min_apart',
            field=models.PositiveSmallIntegerField(default=3, help_text="In hours. How far from their Corporation a character's day has to sit before the list mentions them. A third of the scale above is where the colouring stops calling a distance unremarkable, so a threshold under that lets green rows into the list.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Smallest distance listed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_rhythm_min_difference',
            field=models.PositiveSmallIntegerField(default=0, help_text='In percentage points. How much flatter than the rest of their Corporation a character has to be before the list mentions them. A negative difference means more concentrated than the Corporation, which is the opposite of what this looks for, so those are never listed whatever this says.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Smallest difference listed'),
        ),
    ]
