# Generated by Django 5.2.17 on 2026-09-25 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0019_monthlytax_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='bot_clock_min_concentration',
            field=models.PositiveSmallIntegerField(default=12, help_text='In percent. How closely the payouts have to gather around one time of day before that day has a middle: 100 when all of them fall into one hour, 0 for a day spread perfectly evenly. A day spread evenly over twelve hours comes out at 64, over sixteen at 42, over twenty at 19. Below this - for the character or the rest of their corporation - the middle would be wherever the rounding put it, so the character is left out of this reading.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Least concentrated day with a middle'),
        ),
        migrations.AlterField(
            model_name='monthlytax',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_clock_corp_min_payouts',
            field=models.PositiveSmallIntegerField(default=40, help_text="How many payouts have to be left in the corporation once the character's own are taken out, before its middle of the day is worth comparing against.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Smallest usable yardstick'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_clock_min_apart',
            field=models.PositiveSmallIntegerField(default=3, help_text="In hours. How far from their corporation a character's day has to sit before the list mentions them. A third of the scale above is where the colouring stops calling a distance unremarkable, so a threshold under that lets green rows into the list.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Smallest distance listed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_clock_purge_strong',
            field=models.BooleanField(default=True, help_text="The same for this reading: a character far enough from their corporation to be listed also pulls the corporation's own middle of the day towards themselves, which shortens everybody else's distance.", verbose_name='Leave flagged characters out of the yardstick'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_min_days_per_month',
            field=models.PositiveSmallIntegerField(default=12, help_text='A character is listed once it reaches this many suspicious days within the selected month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Days in a month before a character is listed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_rhythm_busy_hours',
            field=models.PositiveSmallIntegerField(default=8, help_text="How many hours of the day count as the corporation's busy window. A character spread evenly over the clock lands on this share of any window, which is the floor the score measures down to.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)], verbose_name='Length of the busy window'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_rhythm_corp_min_payouts',
            field=models.PositiveSmallIntegerField(default=40, help_text="How many payouts have to be left in the corporation once the character's own are taken out. Below this there is no rhythm to compare against, only noise, and the character is not scored.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Smallest usable yardstick'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_rhythm_min_difference',
            field=models.PositiveSmallIntegerField(default=0, help_text='In percentage points. How much flatter than the rest of their corporation a character has to be before the list mentions them. A negative difference means more concentrated than the corporation, which is the opposite of what this looks for, so those are never listed whatever this says.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Smallest difference listed'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='bot_rhythm_purge_strong',
            field=models.BooleanField(default=True, help_text="A character flat enough to be listed is also part of their corporation's day, and drags it flat with them - which makes everybody else look ordinary. With this on the reading runs twice: once to find them, once with them taken out. A corporation that would fall below the floor above keeps the plain figure.", verbose_name='Leave flagged characters out of the yardstick'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='use_reason',
            field=models.BooleanField(default=False, help_text='Match payments by their reason code instead of by amount alone. Without it a payment is recognised by its amount only, so two corporations owing the same sum, or one corporation owing the same sum twice, cannot be told apart.'),
        ),
    ]
