"""amount_paid keeps what the payment check found, so a transfer of more
than was owed is recorded instead of passing as settled and nothing else.

No backfill from the journal here: the check looks up rows already marked
paid again, so the months the task covers fill in on its next run, and any
other month on its next recalculation - with the same rule that fills every
new row, instead of a second copy of it in this file.
"""

# Generated by Django 5.2.17 on 2026-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0020_clock_concentration_and_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytax',
            name='amount_paid',
            field=models.BigIntegerField(blank=True, help_text="ISK the payment check found for this month, in whole ISK: with reason codes every payment carrying this row's code added up, without them the amount owed once a payment of exactly that turned up. Empty until a payment was seen.", null=True, verbose_name='Amount paid'),
        ),
        migrations.AddField(
            model_name='monthlytax',
            name='payment_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many payments the amount paid is made of.', verbose_name='Payments'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='use_reason',
            field=models.BooleanField(default=False, help_text='Match payments by their reason code instead of by amount alone. With it every payment carrying the code counts, so a corporation can pay in parts, and paying more than it owes is recorded. Without it a payment is recognised by its exact amount only, so two corporations owing the same sum, or one corporation owing the same sum twice, cannot be told apart.'),
        ),
    ]
