# Generated by Django 5.2.17 on 2026-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0021_monthlytax_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytax',
            name='gross_income',
            field=models.BigIntegerField(blank=True, help_text='Bounties earned this month before any corp tax, in whole ISK: the corporation wallet reconciled with the member wallets, so a stretch without ingame tax is counted as well. The amount to pay is worked out from it. Empty on rows written before it was stored.', null=True, verbose_name='Gross PvE income'),
        ),
    ]
