# Generated by Django 5.2.17 on 2026-10-08 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0022_monthlytax_gross_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytax',
            name='unaudited_characters',
            field=models.JSONField(blank=True, default=list, help_text='Characters whose bounties this month showed up in the corporation wallet only, at or above the configured income, as [{id, name, gross}], highest first.', verbose_name='Characters without wallet audit'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='unaudited_min_millions',
            field=models.PositiveSmallIntegerField(default=100, help_text="A character whose bounties reach the corporation wallet but not through a member wallet is listed on the overview once this much gross income a month is backed out of the corporation's slice. Without the member wallet a stretch without ingame tax cannot be seen for that character.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30000)], verbose_name='Income that needs a wallet audit (million ISK)'),
        ),
    ]
