# Generated by Django 5.2.17 on 2026-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0023_wallet_audit_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytax',
            name='calculation_seconds',
            field=models.FloatField(blank=True, help_text='How long the last calculation of this month took, in seconds - reading both journals, the reconciliation and the payment check. Empty on rows written before it was stored.', null=True, verbose_name='Calculation time'),
        ),
    ]
