# Generated by Django 5.2.17 on 2026-10-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0024_monthlytax_calculation_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytax',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Journal date of the transfer that settled this month: the one of exactly the amount owed, or the one that brought the payments up to it. Empty until a payment settled the row.', null=True, verbose_name='Payment date'),
        ),
        migrations.AddField(
            model_name='monthlytax',
            name='paid_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When the payment check first marked this month as paid. Empty on rows marked paid before it was stored.', null=True, verbose_name='Recorded as paid'),
        ),
    ]
