# Generated by Django 5.2.17 on 2026-10-08 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_tax', '0025_payment_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconfiguration',
            name='paid_difference_min_millions',
            field=models.PositiveSmallIntegerField(default=10, help_text='A payment at least this much above or below the amount owed gets a badge next to the amount paid on the overview; a smaller difference is shown without one. 0 flags every difference.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)], verbose_name='Smallest payment difference worth flagging (million ISK)'),
        ),
    ]
